// Authored 16×16 pixel-art tiles for "The Depths" top-down dungeon.
//
// Same convention as spriteGrids.ts: each tile is an array of 16 strings of 16
// characters, every character maps to one palette color ('.' = transparent).
// The palette is IMPORTED from spriteGrids.ts so the dungeon shares the exact
// medieval colors of the rest of the game. tileCanvas() rasterizes each grid
// to an offscreen canvas once and caches it — the engine blits these sprites
// instead of drawing rect-soup, giving the real SNES-style look.
//
// Layers (drawn by DungeonEngine):
//   layer 0  floor_a / floor_b / floor_crack   (non-collidable ground)
//   layer 1  wall / pillar / trap / portal / chest / rune / gate + hero
//   layer 2  torch flames (overhead, drawn after entities) + vignette

import { PALETTE, renderGrid } from './spriteGrids';

export const TILE_GRIDS: Record<string, string[]> = {
  // --- layer 0: floors -------------------------------------------------------
  floor_a: [
    'ssssssssssssssss',
    'sddddddsddddddds',
    'sddddddsddddddds',
    'sddddddsddddddds',
    'sddddddsddddddds',
    'sddddddsddddddds',
    'ssssssssssssssss',
    'sdddddddddddsdds',
    'sdddddddddddsdds',
    'sdddddddddddsdds',
    'sdddddddddddsdds',
    'sdddddddddddsdds',
    'sdddddddddddsdds',
    'sdddddddddddsdds',
    'sdddddddddddsdds',
    'ssssssssssssssss',
  ],
  floor_b: [
    'ssssssssssssssss',
    'sdddddddddsdddds',
    'sdddddddddsdddds',
    'sdddddddddsdddds',
    'sdddddddddsdddds',
    'sdddddddddsdddds',
    'sdddddddddsdddds',
    'ssssssssssssssss',
    'sddddddsddddddds',
    'sddddddsddddddds',
    'sddddddsddddddds',
    'sddddddsddddddds',
    'sddddddsddddddds',
    'sddddddsddddddds',
    'sddddddsddddddds',
    'ssssssssssssssss',
  ],
  floor_crack: [
    'ssssssssssssssss',
    'sddddddsddddddds',
    'sddddddsddddddds',
    'sddddddksdddddds',
    'sdddddkssdddddds',
    'sddddkssddddddds',
    'ssssdkssssssssss',
    'sddkssdddddddsds',
    'sdkssdddddddddds',
    'sdkssdddddddddds',
    'sddksdddddddddds',
    'sddddddsddddddds',
    'sddddddsddddddds',
    'sddddddsddddddds',
    'sddddddsddddddds',
    'ssssssssssssssss',
  ],

  // --- layer 1: obstacles ------------------------------------------------------
  wall: [
    'kkkkkkkkkkkkkkkk',
    'kbbbbbbkbbbbbbbk',
    'kbbbbbbkbbbbbbbk',
    'kbbbbbbkbbbbbbbk',
    'kkkkkkkkkkkkkkkk',
    'kbbbkbbbbbbkbbbk',
    'kbbbkbbbbbbkbbbk',
    'kbbbkbbbbbbkbbbk',
    'kkkkkkkkkkkkkkkk',
    'kbbbbbbkbbbbbbbk',
    'kbbbbbbkbbbbbbbk',
    'kpbbbbbkbbpbbbbk',
    'kkkkkkkkkkkkkkkk',
    'kbbbkbbbbbbkbbbk',
    'kbbbkbbbbbbkbbbk',
    'kbbbkbbbbbbkbbbk',
  ],
  pillar: [
    '................',
    '.....llllll.....',
    '....llllllll....',
    '....lslssssd....',
    '....lslsssd.....',
    '....lslssssd....',
    '....lslssssd....',
    '....lslssssd....',
    '....lslssssd....',
    '....lslssssd....',
    '....lslssssd....',
    '....lslssssd....',
    '....llllllll....',
    '.....dddddd.....',
    '....dddddddd....',
    '................',
  ],

  // --- spike trap (overlay on floor) ------------------------------------------
  trap: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.....l...l...l..',
    '....ll..ll..ll..',
    '....ll..ll..ll..',
    '...lll.lll.lll..',
    '...lll.lll.lll..',
    '..kkkkkkkkkkkk..',
    '................',
  ],

  // --- exit portal -------------------------------------------------------------
  portal_closed: [
    '................',
    '....ssssssss....',
    '...slllllllls...',
    '..slbbbbbbbbls..',
    '..slbbbbbbbbls..',
    '..slbbbbbbbbls..',
    '..slbbkkkkbbls..',
    '..slbbkkkkbbls..',
    '..slbbkkkkbbls..',
    '..slbbkkkkbbls..',
    '..slbbbbbbbbls..',
    '..slbbbbbbbbls..',
    '...slllllllls...',
    '....ssssssss....',
    '..sdddddddddds..',
    '................',
  ],
  portal_open: [
    '................',
    '....ssssssss....',
    '...slllllllls...',
    '..slmmmmmmmmls..',
    '..slBBBBBBBBls..',
    '..slBBmmmmBBls..',
    '..slBmwwwwmBls..',
    '..slBmwwwwmBls..',
    '..slBmwwwwmBls..',
    '..slBmwwwwmBls..',
    '..slBBmmmmBBls..',
    '..slBBBBBBBBls..',
    '...slllllllls...',
    '....ssssssss....',
    '..sdddddddddds..',
    '................',
  ],

  // --- event markers ------------------------------------------------------------
  gate_marker: [
    '................',
    '......rrr.......',
    '.....kkkkkk.....',
    '....kwwwwwwk....',
    '....kwkwwkwk....',
    '....kwwwwwwk....',
    '.....kwkkwk.....',
    '....kksssskk....',
    '...kssdssdssk...',
    '...kssssssssk...',
    '...ksrssssssk...',
    '...kssssssssk...',
    '....kssssssk....',
    '....kMkkkMk.....',
    '................',
    '................',
  ],
  rune_marker: [
    '................',
    '................',
    '......kkk.......',
    '.....kBmmk......',
    '....kBmmmmk.....',
    '.....kBmmk......',
    '......kkk.......',
    '................',
    '................',
    '...kssssssssk...',
    '...kssssssssk...',
    '....kssssssk....',
    '....kssssssk....',
    '...kssssssssk...',
    '..kssssssssssk..',
    '................',
  ],
  chest: [
    '................',
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.knnnnnnnnnnnnk.',
    '.knnnnMMnnnnnnk.',
    '.knnnnMMnnnnnnk.',
    '.kkkkkkkkkkkkkk.',
    '.knnnnnnMMnnnnk.',
    '.knnnnyMynnnnnk.',
    '.knnnnnMnnnnnnk.',
    '.knMnnnnnnnnnMk.',
    '.kMMMMMMMMMMMMk.',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  chest_open: [
    '................',
    '................',
    '..kMMMMMMMMMMk..',
    '..kMMMMMMMMMMk..',
    '..kMMMMMMMMMMk..',
    '..kkkkkkkkkkkk..',
    '..kyYyyyyYyyk...',
    '..kyyYyyyyyyk...',
    '.kyyyyYyyyyyyk..',
    '.kyyyyyYYyyyyk..',
    '.kyyYyyyyyyyyk..',
    '.kyyyyyyYyyyyk..',
    '.kMMMMMMMMMMMMk.',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  trophy: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.......kk.......',
    '......kYYk......',
    '......kYk.......',
    '.......Yk.......',
    '.......Yk.......',
    '.......Yk.......',
    '......kYkYk.....',
    '................',
    '....MMMMMMMM....',
    '...MMMMMMMMMM...',
  ],

  // --- hero (4 facings, 2-frame walk) -------------------------------------------
  hero_down_a: [
    '................',
    '................',
    '....kBBBBBBk....',
    '....kBBBBBBk....',
    '....kBBBBBBk....',
    '....kckckck.....',
    '.....kccck......',
    '....klllllk.....',
    '...kllrrrllk....',
    '...kllrrrllk....',
    '...kllrrrllk....',
    '....klllllk.....',
    '....kMkkMk......',
    '....kMk.kMk.....',
    '................',
    '................',
  ],
  hero_down_b: [
    '................',
    '................',
    '....kBBBBBBk....',
    '....kBBBBBBk....',
    '....kBBBBBBk....',
    '....kckckck.....',
    '.....kccck......',
    '....klllllk.....',
    '...kllrrrllk....',
    '...kllrrrllk....',
    '...kllrrrllk....',
    '....klllllk.....',
    '.....kMMMk......',
    '.....kMMk.......',
    '................',
    '................',
  ],
  hero_up_a: [
    '................',
    '................',
    '....kBBBBBBk....',
    '....kBBBBBBk....',
    '....kBBBBBBk....',
    '....kBBBBBBk....',
    '.....kBBBk......',
    '....klllllk.....',
    '...klrrrrrlk....',
    '...klrrrrrlk....',
    '...klrrrrrlk....',
    '....krrrrrk.....',
    '....kMkkMk......',
    '....kMk.kMk.....',
    '................',
    '................',
  ],
  hero_up_b: [
    '................',
    '................',
    '....kBBBBBBk....',
    '....kBBBBBBk....',
    '....kBBBBBBk....',
    '....kBBBBBBk....',
    '.....kBBBk......',
    '....klllllk.....',
    '...klrrrrrlk....',
    '...klrrrrrlk....',
    '...klrrrrrlk....',
    '....krrrrrk.....',
    '.....kMMMk......',
    '.....kMMk.......',
    '................',
    '................',
  ],
  hero_side_a: [
    '................',
    '................',
    '....kkkkkk......',
    '...kBBBBBBk.....',
    '...kBBBBBBk.....',
    '....kcckck......',
    '....kccck.......',
    '....klllk.......',
    '...kllrrlk......',
    '...kllrrlk......',
    '...kllrrlk......',
    '....klllk.......',
    '....kMkMk.......',
    '....kMkkMk......',
    '................',
    '................',
  ],
  hero_side_b: [
    '................',
    '................',
    '....kkkkkk......',
    '...kBBBBBBk.....',
    '...kBBBBBBk.....',
    '....kcckck......',
    '....kccck.......',
    '....klllk.......',
    '...kllrrlk......',
    '...kllrrlk......',
    '...kllrrlk......',
    '....klllk.......',
    '....kMkMk.......',
    '...kMk.kMk......',
    '................',
    '................',
  ],

  // --- layer 2: torch sconce (overhead, flickers above entities) ----------------
  torch: [
    '................',
    '................',
    '.......t........',
    '......tot.......',
    '......toy.......',
    '.....toyt.......',
    '......oo........',
    '.....kMMk.......',
    '.....kMMk.......',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
};

const canvasCache = new Map<string, HTMLCanvasElement>();

/** Rasterize one tile grid to a cached 16×16 canvas (browser only). */
export function tileCanvas(name: string): HTMLCanvasElement | null {
  const cached = canvasCache.get(name);
  if (cached) return cached;
  const grid = TILE_GRIDS[name];
  if (!grid || typeof document === 'undefined') return null;
  const { width, height, rgba } = renderGrid(grid);
  const canvas = document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext('2d')!;
  const imgData = ctx.createImageData(width, height);
  imgData.data.set(rgba);
  ctx.putImageData(imgData, 0, 0);
  canvasCache.set(name, canvas);
  return canvas;
}

/** All palette chars used by the tile grids — kept valid against spriteGrids. */
export const TILE_PALETTE = PALETTE;
