// Sprite loading with graceful fallback. Primary source: PNGs in
// public/sprites/ (generated by scripts/generate-sprites.ts). If a PNG is
// missing or fails to load, we rasterize the canonical grid from
// spriteGrids.ts directly onto a canvas — so the game always renders.

import { SPRITES, renderGrid } from './spriteGrids';
import { AVATAR_GRIDS } from './avatarGrids';

export type SpriteMap = Record<string, HTMLImageElement>;

const gridCache = new Map<string, string>();

/** data: URL for a sprite, rasterized from its canonical grid. */
export function spriteDataUrl(name: string): string {
  const cached = gridCache.get(name);
  if (cached) return cached;
  const def = SPRITES.find((s) => s.name === name) ?? AVATAR_GRIDS.find((s) => s.name === name);
  if (!def) {
    // Not a canonical grid slot — a custom upload (Theme Forge sprite swap or
    // animation frame). Serve the PNG directly: browsers cache it, CSS keeps
    // it pixelated, and callers gate on existence before asking for it.
    return `/sprites/${name}.png`;
  }
  const grid = def.grid;
  const { width, height, rgba } = renderGrid(grid);
  const canvas = document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext('2d')!;
  const imgData = ctx.createImageData(width, height);
  imgData.data.set(rgba);
  ctx.putImageData(imgData, 0, 0);
  const url = canvas.toDataURL('image/png');
  gridCache.set(name, url);
  return url;
}

/** Preload all sprites as HTMLImageElements; falls back to data URLs on error. */
export async function loadSprites(): Promise<SpriteMap> {
  const map: SpriteMap = {};
  const all = [...SPRITES, ...AVATAR_GRIDS];
  await Promise.all(
    all.map(
      (s) =>
        new Promise<void>((resolve) => {
          const img = new Image();
          img.onload = () => {
            map[s.name] = img;
            resolve();
          };
          img.onerror = () => {
            // Fallback: rasterize the grid onto a canvas and use that as the image source.
            const fallback = new Image();
            fallback.onload = () => {
              map[s.name] = fallback;
              resolve();
            };
            fallback.onerror = () => resolve(); // give up; engine draws a red square
            fallback.src = spriteDataUrl(s.name);
          };
          img.src = `/sprites/${s.name}.png`;
        })
    )
  );
  return map;
}