-- ============================================================
-- 0013: Backfill the guild-chat monotonic seq cursor
-- ============================================================
-- Deployments that applied the sibling checkout's 0011 already have
-- guild_messages *without* the seq column. Timestamp cursors re-deliver the
-- newest message on every poll (JSON loses Postgres' stored microseconds —
-- the "chat repeats like a loop" bug), so chat polling keys on this
-- strictly-monotonic bigint instead. 0011 keeps the column inline for fresh
-- databases; this migration upgrades existing ones.

-- 1. Add the column when missing (no-op on fresh installs where 0011 made it).
ALTER TABLE guild_messages
  ADD COLUMN IF NOT EXISTS seq bigint;

-- 2. Backfill existing rows so the cursor has a total, order-safe history.
--    (created_at, id) is deterministic — identical replays pick the same order.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM guild_messages WHERE seq IS NULL) THEN
    WITH ordered AS (
      SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS n
      FROM guild_messages
    )
    UPDATE guild_messages gm
    SET seq = ordered.n
    FROM ordered
    WHERE gm.id = ordered.id AND gm.seq IS NULL;
  END IF;
END $$;

-- 3. Guarantee every row carries a value before adding the identity.
ALTER TABLE guild_messages
  ALTER COLUMN seq SET NOT NULL;

-- 4. Turn the plain bigint into a monotonic identity sequence (idempotent on
--    fresh installs, which already have it from 0011). Identity-ness is read
--    from pg_attribute.attidentity ('a' = ALWAYS, 'd' = BY DEFAULT) — pg_attrdef
--    .adsrc no longer exists on Postgres 12+.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relname = 'guild_messages'
      AND a.attname = 'seq'
      AND a.attidentity IN ('a', 'd')
      AND n.nspname = current_schema()
  ) THEN
    ALTER TABLE guild_messages
      ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

-- 5. Park the sequence beyond the backfilled history so the next insert gets a
--    value every existing client cursor is already behind.
SELECT setval(
  pg_get_serial_sequence('guild_messages', 'seq'),
  GREATEST(COALESCE((SELECT MAX(seq) FROM guild_messages), 0) + 1, 1),
  false
);
